In [9]:
import pandas as pd
arquivo = pd.read_csv('C:\\Users\\Diego\\Desktop\\DESKTOP\\DATA SCIENCE\\PYTHON\\MACHINE_LEARNING-WINE\\arquivo_csv\\wine_dataset.csv')

In [14]:
arquivo.shape

(6497, 13)

In [15]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [31]:
arquivo['style'] = arquivo['style'].replace('red',0)

In [32]:
arquivo['style'] = arquivo['style'].replace('white',1)

In [33]:
#separando as variaves entre preditoras e variaveis alvo
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [34]:
y

0       0
1       0
2       0
3       0
4       0
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: style, Length: 6497, dtype: int64

In [35]:
x

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [38]:
from sklearn.model_selection import train_test_split

#criando os conjuntos de dados de treino e teste:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [40]:
from sklearn.ensemble import ExtraTreesClassifier
#Criação do modelo:
modelo = ExtraTreesClassifier(n_estimators =100)
modelo.fit(x_treino, y_treino)

#Imprimindo resultados:
resultado = modelo.score(x_teste, y_teste)
print('Acurácia: ', resultado)

Acurácia:  0.9953846153846154

In [55]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4762,7.1,0.36,0.37,4.8,0.019,39.0,114.0,0.99036,3.08,0.49,12.7,7
564,13.0,0.47,0.49,4.3,0.085,6.0,47.0,1.00210,3.30,0.68,12.7,6
5855,6.0,0.33,0.26,5.1,0.051,16.0,119.0,0.99416,3.15,0.41,9.2,5

In [56]:
y_teste[400:403]

4762    1
564     0
5855    1
Name: style, dtype: int64

In [58]:
arquivo[400:404]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
400,6.6,0.735,0.02,7.9,0.122,68.0,124.0,0.9994,3.47,0.53,9.9,5,0
401,7.7,0.260,0.30,1.7,0.059,20.0,38.0,0.9949,3.29,0.47,10.8,6,0
402,12.2,0.480,0.54,2.6,0.085,19.0,64.0,1.0000,3.10,0.61,10.5,6,0
403,11.4,0.600,0.49,2.7,0.085,10.0,41.0,0.9994,3.15,0.63,10.5,6,0

In [60]:
previsoes = modelo.predict(x_teste[400:403])

In [61]:
previsoes

array([1, 0, 1], dtype=int64)